apiVersion: v1
imagePullSecrets:
- name: regcred
kind: ServiceAccount
metadata:
  annotations:
    description: Service account for pulling images
  labels:
    deployedby: clair-yaml
  name: testing-sa
  namespace: testing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.example.com/aggregate-to-monitoring: "true"
    deployedby: aqua-yaml
  name: testing-discovery-cr
  namespace: testing
rules:
- apiGroups: [""]
  resources: ["nodes", "services", "endpoints", "pods", "deployments", "namespaces","componentstatuses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: testing-discovery-crb
  namespace: testing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: testing-discovery-cr
subjects:
  - kind: ServiceAccount
    name: testing-sa
    namespace: testing
