# Create a PVC for the Clair Database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clair-db-pvc
  namespace: testing
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
