apiVersion: v1
kind: Service
metadata:
  labels:
    app: clair-db
    deployedby: clair-yaml
  name: clair-db
  namespace: testing
spec:
  ports:
    - port: 6060
    - port: 6061
  selector:
    app: clair-db
  type: ClusterIP 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clair-db
    deployedby: clair-yaml
  name: clair-db
  namespace: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clair-db
  template:
    metadata:
      labels:
        app: clair-db
      name: clair-db
      namespace: testing
    spec:
      securityContext:
        runAsUser: 70
        runAsGroup: 70
        fsGroup: 11433
      serviceAccount: testing-sa
      restartPolicy: Always
      initContainers:
      - name: clair-db-init
         image: arminc/clair-db:$(date +%Y-%m-%d)
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-db
      containers:
      - name: clair-db
        securityContext:
          privileged: false
        image: arminc/clair-db:$(date +%Y-%m-%d)
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-db
        ports:
        - containerPort: 6060
          protocol: TCP
        - containerPort: 6061
          protocol: TCP
      volumes:
      - name: postgres-db
        persistentVolumeClaim:
          claimName: aqua-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aqua-audit-db
    deployedby: aqua-yaml
  name: aqua-audit-db
  namespace: aqua
spec:
  ports:
    - port: 5432
  selector:
    app: aqua-audit-db
  type: ClusterIP 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aqua-audit-db
    deployedby: aqua-yaml
  name: aqua-audit-db
  namespace: aqua
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aqua-audit-db
  template:
    metadata:
      labels:
        app: aqua-audit-db
      name: aqua-audit-db
      namespace: aqua
    spec:
      securityContext:
        runAsUser: 70
        runAsGroup: 70
        fsGroup: 11433
      serviceAccount: aqua-sa
      restartPolicy: Always
      initContainers:
      - name: aqua-audit-db-init
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: aqua-audit-db
        envFrom:
        - configMapRef:
            name: aqua-csp-db-config
        image: registry.aquasec.com/database:6.5
        command: [ "sh", "-c", "[ -f $PGDATA/server.key ] && chmod 600 $PGDATA/server.key || echo 'OK' " ]
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-db
      containers:
      - name: aqua-audit-db
        securityContext:
          privileged: false
        image: registry.aquasec.com/database:6.5
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: aqua-csp-db-config
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: aqua-audit-db
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-db
        ports:
        - containerPort: 5432
          protocol: TCP
      volumes:
      - name: postgres-db
        persistentVolumeClaim:
          claimName: aqua-audit-db-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqua-web
  namespace: aqua
  labels:
    app: aqua-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aqua-web
  template:
    metadata:
      labels:
        app: aqua-web
      name: aqua-web
    spec:
      securityContext:
        runAsUser: 11431
        runAsGroup: 11433
        fsGroup: 11433
      serviceAccount: aqua-sa
      restartPolicy: Always
      containers:
      - name: aqua-web
        image: registry.aquasec.com/console:6.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        envFrom:
        - configMapRef:
            name: aqua-csp-server-config
        # - secretRef:
        #     name: aqua-csp-server-secret
        env:
        - name: AQUA_PUBSUB_DBPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: aqua-db
        - name: SCALOCK_AUDIT_DBPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: aqua-audit-db
        - name: SCALOCK_DBPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: aqua-db
      #   volumeMounts:
      #   - mountPath: /opt/aquasec/ssl
      #     name: aqua-grpc-web
      #     readOnly: true
      # volumes:
      # - name: aqua-grpc-web
      #   secret:
      #     secretName: aqua-grpc-web
      #     items:
      #     - key: aqua_web.crt
      #       path: cert.pem
      #     - key: aqua_web.key
      #       path: key.pem
      #     - key: rootCA.crt
      #       path: ca.pem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aqua-gateway
  name: aqua-gateway
  namespace: aqua
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aqua-gateway
  template:
    metadata:
      labels:
        app: aqua-gateway
      name: aqua-gateway
    spec:
      securityContext:
        runAsUser: 11431
        runAsGroup: 11433
        fsGroup: 11433
      serviceAccount: aqua-sa
      restartPolicy: Always
      containers:
      - name: aqua-gateway
        image: registry.aquasec.com/gateway:6.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 8443
          initialDelaySeconds: 60
          periodSeconds: 30
        ports:
        - containerPort: 3622
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        envFrom:
        - configMapRef:
            name: aqua-csp-server-config
        env:
        - name: SCALOCK_DBPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: aqua-db
        - name: SCALOCK_AUDIT_DBPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: aqua-audit-db
        volumeMounts:
          - name: "docker-socket-mount"
            mountPath: "/var/run/docker.sock"
      volumes:
        - name: "docker-socket-mount"
          hostPath:
            path: "/var/run/docker.sock"
